version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: pmp_db_prod
    restart: always
    environment:
      - POSTGRES_USER=pmpuser
      - POSTGRES_PASSWORD=pmppassword
      - POSTGRES_DB=pmpdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pmp-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pmp_backend_prod
    restart: always
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgresql://pmpuser:pmppassword@db:5432/pmpdb
      - JWT_SECRET=your-super-secret-jwt-key-for-production
      - JWT_EXPIRES_IN=7d
    ports:
      - "5000:5000"
    networks:
      - pmp-network
    command: sh -c "npx prisma migrate deploy && npm start"

  frontend:
    build:
      context: ./frontend
    container_name: pmp_frontend_prod
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000 # URL backend dari perspektif browser
    networks:
      - pmp-network

networks:
  pmp-network:
    driver: bridge

volumes:
  postgres_data: